language: csharp
solution: ./src/Selenium.Essentials/Selenium.Essentials.sln
mono: none
dotnet: 2.1.502
dist: trusty

script:
 - dotnet restore src/Selenium.Essentials/Selenium.Essentials.sln
 - dotnet build src/Selenium.Essentials/Selenium.Essentials.sln
 - dotnet test test/Selenium.Essentials.UnitTests/Selenium.Essentials.UnitTests.csproj
 
addons:
  sauce_connect: true
