language: csharp
solution: ./src/Selenium.Essentials/Selenium.Essentials.sln
mono: none
dotnet: 3.1
dist: trusty

script:
 - dotnet restore src/Selenium.Essentials/Selenium.Essentials.sln
 - dotnet build src/Selenium.Essentials/Selenium.Essentials.sln
 - dotnet test test/Selenium.Essentials.UnitTests/Selenium.Essentials.UnitTests.csproj
 - dotnet test test/Selenium.Essentials.IntegrationTests/Selenium.Essentials.IntegrationTests.csproj
 - travis_wait 30 dotnet test example/Selenium.Essentials.SampleTest/Selenium.Essentials.SampleTest.csproj
 
addons:
  sauce_connect: true
