language: csharp
solution: ./src/Selenium.Essentials/Selenium.Essentials.sln
mono: none
dotnet: 2.1.502
dist: trusty

script:
 - cd src/Selenium.Essentials
 - dotnet restore 
 - dotnet build
 - dotnet test test/Selenium.Essentials.UnitTests/Selenium.Essentials.UnitTests.csproj
 
addons:
  sauce_connect: true
